data_root: /home/sakurai/git2/lab2021/data/token_classification
output_dir: /home/sakurai/git2/lab2021/experiments/result
exp_name: sequence_classification
model_names: linear
# model_names: lstm
#pretrained: /home/mtakahashi/work/lab2021/experiments/result/test/linear_freeze/checkpoints/epoch=07-val_loss=0.500.ckpt
#pretrained: /home/mtakahashi/work/lab2021/experiments/result/test/Bilstm_freeze/checkpoints/epoch=02-val_loss=0.427.ckpt
##pretrained: /home/mtakahashi/work/lab2021/experiments/result/test/lstm_freeze/checkpoints/epoch=01-val_loss=0.417.ckpt
seed: 42
dataset_params:
  train_batchsize: 40
  val_batchsize: 20
model:
  should_freeze_bert_model: True
  n_workers: 20
trainer:
  gpus: [0]
  max_epochs: 30
  log_every_n_steps: 100
  # fast_dev_run: True